export const SAGA_EDIT_FORM_TITLE = "SAGA_EDIT_FORM_TITLE";
export const SAGA_EDIT_FORM_INTEREST = "SAGA_EDIT_FORM_INTEREST";
export const SAGA_EDIT_FORM = "SAGA_EDIT_FORM";
export const SAGA_ADD_TO_CART = "SAGA_ADD_TO_CART";
